[[headers]]
  for = "*.br"
  [headers.values]
    Content-Encoding = "br"

[[headers]]
  for = "*.js.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"

[[headers]]
  for = "*.wasm.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"
